export const GET_COUPLES_PENDING = 'GET_COUPLES_PENDING';
export const GET_COUPLES_SUCCESS = 'GET_COUPLES_SUCCESS';
export const GET_COUPLES_ERROR = 'GET_COUPLES_ERROR';

export const GET_COUPLES_ID_PENDING = 'GET_COUPLES_ID_PENDING';
export const GET_COUPLES_ID_SUCCESS = 'GET_COUPLES_ID_SUCCESS';
export const GET_COUPLES_ID_ERROR = 'GET_COUPLES_ID_ERROR';

export const ADD_COUPLE_PENDING = 'ADD_COUPLE_PENDING';
export const ADD_COUPLE_SUCCESS = 'ADD_COUPLE_SUCCESS';
export const ADD_COUPLE_ERROR = 'ADD_COUPLE_ERROR';

export const DELETE_COUPLE_PENDING = 'DELETE_COUPLE_PENDING';
export const DELETE_COUPLE_SUCCESS = 'DELETE_COUPLE_SUCCESS';
export const DELETE_COUPLE_ERROR = 'DELETE_COUPLE_ERROR';

export const EDIT_COUPLE_PENDING = 'EDIT_COUPLE_PENDING';
export const EDIT_COUPLE_SUCCESS = 'EDIT_COUPLE_SUCCESS';
export const EDIT_COUPLE_ERROR = 'EDIT_COUPLE_ERROR';

export const USERSEARCHED_SUCCESS = 'USERSEARCHED_SUCCESS';
export const USERSEARCHED_ERROR = 'USERSEARCHED_ERROR';