export const GET_BILLS_PENDING = 'GET_BILLS_PENDING';
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
export const GET_BILLS_ERROR = 'GET_BILLS_ERROR';

export const ADD_BILL_PENDING = 'ADD_BILL_PENDING';
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS';
export const ADD_BILL_ERROR = 'ADD_BILL_ERROR';

export const DELETE_BILL_PENDING = 'DELETE_BILL_PENDING';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const DELETE_BILL_ERROR = 'DELETE_BILL_ERROR';

export const EDIT_BILL_PENDING = 'EDIT_BILL_PENDING';
export const EDIT_BILL_SUCCESS = 'EDIT_BILL_SUCCESS';
export const EDIT_BILL_ERROR = 'EDIT_BILL_ERROR';