export const GET_EXPENSES_PENDING = 'GET_EXPENSES_PENDING';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_ERROR = 'GET_EXPENSES_ERROR';

export const ADD_EXPENSE_PENDING = 'ADD_EXPENSE_PENDING';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_ERROR = 'ADD_EXPENSE_ERROR';

export const DELETE_EXPENSE_PENDING = 'DELETE_EXPENSE_PENDING';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR';

export const EDIT_EXPENSE_PENDING = 'EDIT_EXPENSE_PENDING';
export const EDIT_EXPENSE_SUCCESS = 'EDIT_EXPENSE_SUCCESS';
export const EDIT_EXPENSE_ERROR = 'EDIT_EXPENSE_ERROR';